### ISSUE TITLE
Current emergency appeals and their coverage percentage within a specific region

### ISSUE THREAD

**Issue by gulfaraz** [IFRCGo/how-to-use-the-go-api#10]
Add an example which shows current emergency appeals and their coverage percentage for a region

Possibly adding a link for pulling latest documents associated with that appeal code (using api/v2/appeal_document and connecting to the MDR code)

@JonathanGarro what is MDR?

**Comment by JonathanGarro** [comment]
@gulfaraz Sorry, I sometimes use too many acronyms! MDR is the prefix on emergency appeal codes. The naming scheme is: 

MDR + Country ISO + sequential numbering.

See [appeal page](https://www.ifrc.org/en/publications-and-reports/appeals/?ac=&at=246&c=&co=&dt=1&f=&re=&t=&ti=&zo=) for examples.

**Comment by JonathanGarro** [comment]
@gulfaraz Thanks for setting this up. I've played around with this to test grabbing the URL and here is what I've found: 

- /api/v2/appeal_document/ does not have the MDR code we are looking for but does have the doc URL. But it contains the following relevant endpoint: `appeal`, which appears to just be sequentially numbered by the system. That appeal code is not useful to end users.
- /api/v2/appeal/ has that same `appeal` endpoint, which you can use a lookup with to grab the `code` endpoint (that's the one referenced above which _is_ of use here).

I lay that out because I think most users who would want to do a plain text search for the MDR code in order to grab the URL for the document would need to connect those two calls. Just FYI as that is how I'll be documenting on my end.

**Comment by gulfaraz** [comment]
@JonathanGarro https://ifrcgo.org/how-to-use-the-go-api#example4
