### ISSUE TITLE
Add example which shows how to authorize

### ISSUE THREAD

**Issue by gulfaraz** [IFRCGo/how-to-use-the-go-api#9]
Add an example which illustrates how a user can access an API which requires authorization.

Todo,
- [x] decide which API - "show all open vs. filled surge requests" from @JonathanGarro's email
- [ ] create code snippets for each language
- [ ] generate and add charts

**Comment by JonathanGarro** [comment]
Step zero for the list above is how to actually generate that token, here is that walkthrough again just for posterity until we migrate to the km platform: 

## Generating a Token
### What You’ll Need
- **An API tool**: For this walkthrough, we will be using Postman, a popular service with a free account option. There are many others, and the basic steps outlined here should work with them as well.
- **GO Login Credentials**: In order to generate a token, you need to have a GO account with Red Cross Red Crescent permissions. 

#### What are Authentication Tokens?
Information in GO is segregated by audience. Some pieces of information are fine for the general public to access, while other pieces are limited to only members of the Red Cross Red Crescent Movement. When you create a user profile on GO as a member of a national society, your account is given access to that more private level of information, and when we access that data via the API, the system needs a way to verify that we are permitted to see it. That’s where tokens come in. 

A token is passed to the server along with whatever your search request is, as a way to tell it that we’re allowed to see what we’re requesting. Think of it like a secret handshake to get into the members-only club. 

#### How Do I Get An Authentication Token?
From the API Basics article, you’ll remember that the four key elements of interacting with an API are: 
* The endpoint
* The method
* The headers
* The data (or body)

##### Endpoint
The endpoint here is:

`https://prddsgocdnapi.azureedge.net/get_auth_token`

The base URL is telling the request to ping the GO server. The `/get_auth_token` is accessing the token generator. 

##### Method
We need to generate one with a special API call. There are a number of methods for interacting with APIs, depending on what you’re trying to do with the data in the server. Most of the time, we’re just reading data, and that means using the `GET` method. But in some scenarios, including this step of generating a token, we need to use `POST`. That’s because we’re sending a request to the server to actually create a new resource (in this case, our token). 

##### Headers
This isn’t a query in the same sense as other interactions with the GO server, so we don’t have any parameters to include. However, there is one header that is a good idea to add here: 

Key (Header Name): `Content-Type`
Value (Header Value): `application/json`

Understanding the reason for this specification isn’t vital to your understanding of this process, but if you’re interested, the short explanation is that this header tells the server what media type it is dealing with, and then that the data should be formatted as JSON. Other media types include: 

* audio
* font
* example
* image
* message
* model
* multipart
* text
* video

##### Data
Here is where the actual request to the server is being stored. As we’re dealing with JSON formatting, our data here needs to be formatted as such. We’re going to include the following in the body: 

```javascript
{
"username": "myusername", 
"password": "mypassword"
}
```

You would update the text above with your own GO username (case-sensitive) and password, while _keeping the quotes around all of the elements_. So as an example, my own snippet would look like this: 

```javascript
{
"username": "Jonathan", 
"password": "This_is_my_secret_password"
}
```

#### Putting It All Together
1. Log into Postman. At the top left of the window, click `New`
2. In the window that pops up, click on `Request`

![image](https://user-images.githubusercontent.com/8890661/109310221-40fd0400-7812-11eb-9a64-bd93f1310be9.png)

3. In the main window that appears, click `GET` and from the dropdown, select `POST`
4. In the field labeled `Enter request URL` type `https://prddsgocdnapi.azureedge.net/get_auth_token`
5. Click `Headers` below the URL bar, and enter: 
	1. Key: `Content-Type`
	2. Value: `application/json`
	3. Make sure the checkbox to the left of `Content-Type` is checked

![image](https://user-images.githubusercontent.com/8890661/109310284-52461080-7812-11eb-93a6-58e7b86920bc.png)

6. Click `Body`, then select `raw` from the menu below. The last element should say `JSON` - if not, select it. Then enter `{"username": “your-username”, "password": “your-password”}`, changing where you see “your-username” and “your-password” to match the credentials you use to log into GO. Remember to keep quotes around all of those elements!

![image](https://user-images.githubusercontent.com/8890661/109310349-6427b380-7812-11eb-9661-1f319233f50b.png)

7. Click `Send` at the top right. If everything was entered correctly, you should get a response from the server with the following:

```javascript
{
    “token”: “redacted, but you would see a long string of characters here!”,
    “username”: “Jonathan”,
    “first”: “Jonathan”,
    “last”: “Garro”,
    “expires”: “2021-02-23T19:33:04.456Z”,
    “id”: 1316
}
```

**Comment by JonathanGarro** [comment]
![image](https://user-images.githubusercontent.com/8890661/109310136-24f96280-7812-11eb-9b6d-6fb5b813c2a4.png)

**Comment by gulfaraz** [comment]
@JonathanGarro I realized that we cannot have a live example here for authorized requests without making the password public. So I added examples that show [how to get](https://ifrcgo.org/how-to-use-the-go-api/#example0) and [use the GO_API_AUTHORIZATION_TOKEN](https://ifrcgo.org/how-to-use-the-go-api/#example3) without building a live chart. Please let me know if anything else needs to change for this item.

**Comment by gulfaraz** [comment]
@JonathanGarro I realized that we cannot have a live example here for authorized requests without making the password public. So I added examples that show [how to get](https://ifrcgo.org/how-to-use-the-go-api/#example0) and [use the GO_API_AUTHORIZATION_TOKEN](https://ifrcgo.org/how-to-use-the-go-api/#example3) without building a live chart. Please let me know if anything else needs to change for this item.
